# Buildspec file for AWS CodeBuild
version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip3 install --upgrade pip
            - python3 -m venv .venv
            - .venv/bin/activate
            - cd backend
            - pip install -r requirements.txt
            - pip install pytest pytest-cov
            - cd ..

    build:
        commands:
            - .venv/bin/activate
            - cd backend
            #run pytest tests
            # Stop after first test failure, stop after first test failure, collect coverage for all project files, Save coverage report in Cobertura XML
            - pytest --maxfail=1 --junitxml=test-reports/junit.xml --cov=. --cov-report=xml:test-reports/coverage.xml
            #zip up backend into a dist folder, for elastic beanstalk deployment :
            - mkdir -p dist && zip -r dist/backend.zip . \
              -x ".venv/*" "__pycache__/*" ".pytest_cache/*" ".env"
              # Exclude venv, Python caches, pytest cache, and .env file from the zip
            - cd ..

artifacts:
    files:
        - backend/dist/backend.zip # Upload dist/backend.zip as the build artifact (for deploy stage)

reports:
    tests: # First report group: test results
        files:
            - backend/test-reports/junit.xml
        file-format: JUNITXML # Format so CodeBuild can parse test outcomes
    coverage: # Second report group: code coverage
        files:
            - backend/test-reports/coverage.xml
        file-format: COBERTURAXML # Format so CodeBuild can parse coverage data

cache:
    paths:
        - "/root/.cache/pip/**/*" # Cache pip’s downloaded wheels/packages between builds for speed
